config/routes.rb
Rails.application.routes.draw do
  root 'app#landing'
  get '/team', to: 'app#team'
  get '/contact', to: 'app#contact'
  post 'gossip/:id', to: 'comment#create'

  resources :session, only: [:new, :create, :destroy]
  resources :gossip do
    resources :comment
  end
  resources :like, only: [:create, :destroy]
  resources :user
  resources :city
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :gossip_taggeds
    has_many :tags, through: :gossip_taggeds
    has_many :comments
    has_many :likes
    validates :title, presence: true, length: { in: 3..14 }
    validates :content, presence: true
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
    include GossipHelper
    include SessionHelper
    before_action :authenticate_user, only: [:new]

    def index
        @gossips = Gossip.all
        @users = User.all
    end
    
    def show
        @users = User.all
        @gossip = Gossip.find(params[:id])
        @user = User.find(@gossip.user_id)
        @city = City.find(@user.city_id)
        @comments = Comment.all
    end
    
    def new
       @tags = Tag.all
    end
    
    def create
        @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: current_user.id, tag_id: params[:tag].to_i)

        if @gossip.save
            flash
            render "/gossip/index_sucess"
        else
            render "/gossip/new_error"
        end
    end
    
    def edit
        @gossip = Gossip.find(params[:id])
    end
    
    def update
        @gossip = Gossip.find(params[:id])
        if @gossip.update(post_params)
            redirect_to gossip_index_path
        else
            render '/gossip/edit_error'
        end
    end
    
    def destroy
        @gossip = Gossip.find(params[:id])
        destroy_likes(@gossip)
        @gossip.destroy
        redirect_to gossip_index_path
    end

    private

    def post_params
        params.require(:gossip).permit(:title, :content)
    end

    def authenticate_user
        unless current_user
            flash[:danger] = "Please log in."
        redirect_to new_session_path
        end
    end
end

app/helpers/gossip_helper.rb
module GossipHelper
    def destroy_likes(gossip)
        Like.all do |like|
            if like.gossip_id = gossip.id
                like.destroy
            end
        end
    end
end

app/views/gossip/edit.html.erb
<h1 class='title'>Edit Gossip</h1>
<div class="new_gossip">
<%= form_for @gossip do |f|%>
      <h4 class='title'>Title :</h4>
      <%= f.text_field :title %><br>
      <h4 class='title'>content :</h4>
      <%= f.text_area :content%><br>
      <button type="submit" class='my-btn make-gossip-button'>Submit</button>
<%end%> 
</div>

app/views/gossip/edit_error.html.erb
<% if @gossip.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Couldn't create Gossip : </strong>
        <% @gossip.errors.full_messages.each do |message| %>
        <%= message + "."%>
        <% end %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="outline: none;">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

<h1 class='title'>Edit Gossip</h1>
<div class="new_gossip">
<%= form_for @gossip do |f|%>
    <h4 class='title'>Title :</h4>
    <%= f.text_field :title %><br>
    <h4 class='title'>content :</h4>
    <%= f.text_area :content%><br>
    <button type="submit" class='my-btn make-gossip-button'>Submit</button>
<%end%>
</div>

app/views/gossip/index.html.erb
<div class="make-gossip">
    <form action= <%= new_gossip_path %> method="GET">
        <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
        <input type="submit" class="make-gossip-button my-btn" value="send Gossip">
    </form>
</div>


<h1 class="title display-3">The Gossips</h1> <%=@alert%>

<div class="index_page">
    <%@gossips.each do |gossip|%>
        <a href="gossip/<%=gossip.id%>" class="my-btn gossip_index" style="text-decoration: none;">
            <p style="font-size : 70%; text-align:right; padding-right: 10px;"><%=Like.count {|l| l.gossip_id == gossip.id}%>❤</p>
            <h3 class="title" style="text-decoration:none;"><%=gossip.title%></h3>
            <p style="text-decoration:none;"><%=@users.find_by(id: gossip.user_id).login%></p>
            <p style="font-size : 70%; text-align:left; padding-left: 10px;"><%=Comment.count {|c| c.gossip_id == gossip.id}%> comment(s)</p>
        </a>
    <%end%>
</div>

app/views/gossip/index_sucess.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Your Gossip has been Uploaded.</strong> Check it out now !
  <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="outline: none;">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<%if current_user%>
<div class="make-gossip">
    <form action= <%= new_gossip_path %> method="GET">
        <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
        <input type="submit" class="make-gossip-button my-btn" value="send Gossip">
    </form>
</div>
<%end%>
<h1 class="title display-3">The Gossips</h1> <%=@alert%>

<div class="index_page">
    <%Gossip.all.each do |gossip|%>
            <a href="gossip/<%=gossip.id%>" class="my-btn gossip_index" style="text-decoration: none;">
                <p style="font-size : 70%; text-align:right; padding-right: 10px;"><%=Like.count {|l| l.gossip_id == gossip.id}%>❤</p>
                <h3 class="title" style="text-decoration:none;"><%=gossip.title%></h3>
                <p style="text-decoration:none;"><%=User.all.find_by(id: gossip.user_id).login%></p>
                <p style="font-size : 70%; text-align:left; padding-left: 10px;"><%=Comment.count {|c| c.gossip_id == gossip.id}%> comment(s)</p>
            </a>
    <%end%>
</div>

app/views/gossip/new.html.erb
<h1 class='title'>Send your own Gossip</h1>
<div class="new_gossip">
      <%= form_tag(gossip_index_path) do -%>
            <div><h4 class='title'>Title :</h4><%= text_field_tag 'title' %></div><br>
            <div><h4 class='title'>content :</h4><%=text_area_tag 'content'%></div><br>
            <%=select_tag "tag", options_for_select(["1","2","3","4"])%>
            <div><button type="submit" class='my-btn make-gossip-button'>Submit</button></div>
      <% end -%>
</div>

      

app/views/gossip/new_error.html.erb
<% if @gossip.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Couldn't create Gossip : </strong>
        <% @gossip.errors.full_messages.each do |message| %>
        <%= message + "."%>
        <% end %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="outline: none;">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>
<h1 class='title'>Send your own Gossip</h1>
<%= form_tag(gossip_index_path) do -%>
      <div><h4 class='title'>Title :</h4><%= text_field_tag 'title' %></div><br>
      <div><h4 class='title'>content :</h4><%=text_area_tag 'content'%></div><br>
      <%=select_tag "tag", options_for_select(["1","2","3","4"])%>
      <div><button type="submit" class='my-btn make-gossip-button'>Submit</button></div>
<% end -%>

app/views/gossip/show.html.erb
<div class="gossip-show-section">
    <div class="gossip-section">
        <div class="gossip-title title">
            <h2><%=@gossip.title%></h2>
        </div>
        <div class="gossip-content title">
            <%=@gossip.content%><br>
        </div>
        <div class="user-info title">
            By  : <%=@user.login%><br>
            From : <%=@city.name%><br>
        </div>

        <a href="<%=user_path(@user.id)%>" class="my-btn-user" style="text-decoration: none;">Go to user</a>
        <%if current_user && current_user.id == @user.id%>
            <a href="<%= gossip_path(@gossip.id) %>" class="my-btn-destroy" style="text-decoration: none;" data-confirm="êtes-vous sur?" data-method="DELETE">Supprimer la catégorie</a>
            <a href=<%=edit_gossip_path%> class="my-btn" style="text-decoration: none; ">Edit Gossip</a>
        <%end%>
        <div class="likes">
            <%if current_user%>
                <%if Like.find_by(user_id: current_user.id, gossip_id: @gossip.id)%>
                    <a href="<%= like_path(Like.find_by(user_id: current_user.id, gossip_id: @gossip.id).id) %>" class='unlove-btn', data-method="DELETE">❤</a>
                <%end%>
                <%unless Like.find_by(user_id: current_user.id, gossip_id: @gossip.id)%>
                    <%= form_tag(like_index_path) do -%>
                        <%=hidden_field_tag "gossip_id", @gossip.id%>
                        <button type="submit" class='love-btn' style="border-radius:50%;">❤</button>
                    <% end -%>
                <%end%>
            <%end%>
        </div>
    </div>

    <div class="comment-section">
        <h3 class="title" style="text-align:left">Comment section</h3>
        <div class="comments">
            <% @comments.each do |c|%>
                <%if c.gossip_id == @gossip.id%>
                    <div class="comment">
                        <p class="title"><%=@users.find(c.user_id).login%> : <small><%=c.content%></small></p>
                        <div class="edit-comment">
                            <%if current_user.id == c.user_id%>
                                <a href=<%=edit_gossip_comment_path(@gossip.id, c.id)%> class="modify-comment" style="text-decoration: none;">Modify</a>
                                <a href="<%= gossip_comment_path(@gossip.id, c.id) %>" class="del-comment" style="text-decoration: none;" data-method="DELETE">Delete</a>
                            <%end%>
                        </div>
                    </div>
                <%end%>
            <%end%>
        </div>

        <%if current_user%>
            <div class="create-comment">
                <%= form_for gossip_comment_index_path @gossip.id do |f|-%>
                    <div><%=f.text_area 'content'%></div>
                    <div><button type="submit" class='my-btn make-gossip-button'>leave a comment</button></div>
                <% end -%>
            </div>
        <%end%>
    </div>
</div>