config/routes.rb
Rails.application.routes.draw do
  root 'app#landing'
  get '/team', to: 'app#team'
  get '/contact', to: 'app#contact'
  post 'gossip/:id', to: 'comment#create'

  resources :session, only: [:new, :create, :destroy]
  resources :gossip do
    resources :comment
  end
  resources :like, only: [:create, :destroy]
  resources :user
  resources :city
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/controllers/city_controller.rb
class CityController < ApplicationController
    include SessionHelper
    
    def index
        @cities = City.all
    end

    def show
        @city = City.find(params[:id])
        @gossips = Gossip.all
        @users = User.all
    end
end

app/helpers/city_helper.rb
module CityHelper
end

app/views/city/index.html.erb
<% @cities.count do |city|%>
    <div style="margin : 30px; text-align : left;">
        <a href="<%=city_path(city.id)%>"class="my-btn" style="text-decoration: none"><%=city.name%></a>
    </div>
<%end%>

app/views/city/show.html.erb
<div class="make-gossip">
    <form action= <%= new_gossip_path %> method="GET">
        <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
        <input type="submit" class="make-gossip-button my-btn" value="send Gossip">
    </form>
</div>

<h1 class="title display-4"><%=@city.name%> Gossips</h1>

<div class="index_page">
    <% @gossips.count do |gossip|%>
        <% if @users.find(gossip.user_id).city_id == @city.id %>
            <a href="<%=gossip_path(gossip.id)%>" class="my-btn gossip_index" style="text-decoration: none;">
                <p style="font-size : 70%; text-align:right; padding-right: 10px;"><%=Like.count {|l| l.gossip_id == gossip.id}%>❤</p>
                <h3 class="title" style="text-decoration:none;"><%=gossip.title%></h3>
                <p style="text-decoration:none;"><%=User.all.find_by(id: gossip.user_id).login%></p>
                <p style="font-size : 70%; text-align:left; padding-left: 10px;"><%=Comment.count {|c| c.gossip_id == gossip.id}%> comment(s)</p>
            </a>
        <%end%> 
    <%end%>
</div>