config/routes.rb
Rails.application.routes.draw do
  root 'app#landing'
  get '/team', to: 'app#team'
  get '/contact', to: 'app#contact'
  post 'gossip/:id', to: 'comment#create'

  resources :session, only: [:new, :create, :destroy]
  resources :gossip do
    resources :comment
  end
  resources :like, only: [:create, :destroy]
  resources :user
  resources :city
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city, optional: true
    has_many :private_messages
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
    has_many :comments
    has_many :likes
    validates :last_name, presence: true
    validates :first_name, presence: true
    validates :login, presence: true, uniqueness: true, length: {minimum: 3, maximum: 14}
    validates :email, presence: true, uniqueness: true
    has_secure_password



    def remember(remember_token)
        remember_digest = BCrypt::Password.create(remember_token)
        self.update(remember_digest: remember_digest)
      end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(post_params)

    if @user.save
        log_in(@user)
        redirect_to gossip_index_path
    else
        render new_user_path
    end
  end

  private

  def post_params
    params[:city_id] = rand(1..10)
    params.permit(:first_name, :last_name, :login, :password, :email, :city_id)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/new.html.erb
<%= form_tag(user_index_path) do -%>
    <p>Email</p><%= email_field_tag 'email', nil%>
    <p>First name</p><%= text_field_tag 'first_name', nil%>
    <p>Last name</p><%= text_field_tag 'last_name', nil%>
    <p>Username</p><%= text_field_tag 'login', nil%>
    <p>Password</p><%= password_field_tag 'password', nil%>
    <div><button type="submit" class='my-btn-user'>Submit</button></div>
<% end -%>

app/views/user/show.html.erb
<div class="title">
<h1>Login : <%=@user.login%></h1>

<p>Name : <%=@user.first_name%> <%=@user.last_name%></p>
<p>Description : <%=@user.description%></p>
<p>Email : <%=@user.email%></p>
<p>City : <%=City.find(@user.city_id).name%></p>
</div>