config/routes.rb
Rails.application.routes.draw do
  root 'app#landing'
  get '/team', to: 'app#team'
  get '/contact', to: 'app#contact'
  post 'gossip/:id', to: 'comment#create'

  resources :session, only: [:new, :create, :destroy]
  resources :gossip do
    resources :comment
  end
  resources :like, only: [:create, :destroy]
  resources :user
  resources :city
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    has_many :likes
    belongs_to :user
    belongs_to :gossip
    validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :gossip_taggeds
    has_many :tags, through: :gossip_taggeds
    has_many :comments
    has_many :likes
    validates :title, presence: true, length: { in: 3..14 }
    validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city, optional: true
    has_many :private_messages
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
    has_many :comments
    has_many :likes
    validates :last_name, presence: true
    validates :first_name, presence: true
    validates :login, presence: true, uniqueness: true, length: {minimum: 3, maximum: 14}
    validates :email, presence: true, uniqueness: true
    has_secure_password



    def remember(remember_token)
        remember_digest = BCrypt::Password.create(remember_token)
        self.update(remember_digest: remember_digest)
      end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
    include SessionHelper
end

app/controllers/city_controller.rb
class CityController < ApplicationController
    include SessionHelper
    
    def index
        @cities = City.all
    end

    def show
        @city = City.find(params[:id])
        @gossips = Gossip.all
        @users = User.all
    end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController

    def create
        @like = Like.new
        @like.user_id = current_user.id
        @like.gossip_id = params[:gossip_id].to_i
        @like.comment_id = 1
        @like.save
        redirect_to gossip_path(params[:gossip_id].to_i)
    end

    def destroy
        gossip_id = Like.find(params[:id]).gossip_id
        Like.find(params[:id]).destroy
        redirect_to gossip_path(gossip_id)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(post_params)

    if @user.save
        log_in(@user)
        redirect_to gossip_index_path
    else
        render new_user_path
    end
  end

  private

  def post_params
    params[:city_id] = rand(1..10)
    params.permit(:first_name, :last_name, :login, :password, :email, :city_id)
  end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
    def destroy_likes(gossip)
        Like.all do |like|
            if like.gossip_id = gossip.id
                like.destroy
            end
        end
    end
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/session_helper.rb
module SessionHelper
    def current_user
        if session[:user_id]
        current_user = User.find_by(id: session[:user_id])

        # nous allons vérifier s'il y a bien un cookie contenant l'id de notre utilisateur  
        elsif cookies[:user_id]

         # nous allons trouver l'utilisateur en DB à partir du cookie qui stocke le user_id
         user = User.find_by(id: cookies[:user_id])

          if user

            # nous allons prendre le remember_token stocké en cookie, le hasher, puis le comparer avec notre remember_digest stocké en base
            remember_token = cookies[:remember_token]
            remember_digest = user.remember_digest
            user_authenticated = BCrypt::Password.new(remember_digest).is_password?(remember_token)

                # si tout est bon, il ne nous reste plus qu'à souhaiter bienvenue à l'utilisateur !
                if user_authenticated
                    log_in user
                    current_user = user
                end
            end
    end
    
    def log_in(user)
        session[:user_id] = user.id
    end

    def log_out(user)
        session.delete(:user_id)
        forget(user)
      end

      
end
def remember(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64
  
    # j'ai mon token, je vais stocker son digest en base de données :    
    user.remember(remember_token)
  
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  
  end

  def forget(user)

    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
  
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  
  end

app/helpers/user_helper.rb
module UserHelper
end

app/views/app/contact.html.erb
<p class="title contact">Si tu veux me contacter, envoie moi un mail à noahancolie@gmail.com</p>

app/views/app/landing.html.erb
<div class="landing-div mydiv" id="mydiv">
    <h1 class="display-2 title">The gossip Project</h1>
  <p class="lead text-muted">Where you can share all about your co-workers</p>
  <hr class="my-4">
  <p class="lead">
    <a class="btn btn-lg my-btn" href=<%=gossip_index_path%> role="button">Go to Gossips</a>
  </p>
</div>

app/views/app/team.html.erb
<h1 class='title'>Voici notre équipe : <br><br></h1>
<h3 class='team'>Larbi Ait Hamadouche<br>Loic Paolucci<br>Sami Kannouch<br>Fransceco Feodor<br>Adrien Benaceur</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appli</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@500&display=swap" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand title" href="/">The Gossip Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
       <div class="navbar-nav">
         <a class="nav-item nav-link active" href=<%=gossip_index_path%>>Gossips <span class="sr-only">(current)</span></a>
         <a class="nav-item nav-link active" href=<%=city_index_path%>>Cities <span class="sr-only">(current)</span></a>
         <a class="nav-item nav-link" href=<%=contact_path%>>Contact</a>
         <a class="nav-item nav-link" href=<%=team_path%>>Team</a>
       </div>
      </div>
      <div class="dropdown">
      <%unless current_user%>
        <button class="my-btn-user dropdown-toggle" type="button" data-toggle="dropdown">Offline
      <%else%>
        <button class="my-btn-user dropdown-toggle" type="button" data-toggle="dropdown">Online
      <%end%>
      <span class="caret"></span></button>
      <ul class="dropdown-menu">
        <%unless current_user%>
          <li class="good-log title"><a href="<%=new_session_path%>">Log in</a></li>
          <li class="good-log title"><a href="<%=new_user_path%>">Sign up</a></li>
        <%end%>
        <%if current_user%>
          <li class="bad-log title"><%= link_to "Log out", session_path(session.id), method: :delete %></li>
        <%end%>
      </ul> 
      </div>
    </nav>
  </header>
  <body>
  
    <%= yield %>
  </body>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      $('.alert').alert()
    })

    const cursor = document.querySelector('.cursor');

    document.addEventListener('mousemove', e => {
      cursor.setAttribute('style', 'top:' + (e.pageY - 10) + "px; left:" + (e.pageX - 10) + "px;")
    })

    document.addEventListener('click', ()=>{
      cursor.classList.add('expand');

      setTimeout(() => {
        cursor.classList.remove('expand');  
      }, 500);
    })
  </script>
</html>